mysite/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve


urlpatterns = [
    path('', include('tommy.urls')),
    path('staff/', include('staff.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static')
    }),
]

# Configure admin page titles
admin.site.site_header = "Tommy Lanaguage App Admin"

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    # Main page for content admins to navigate adding and editing content
    path('', views.StaffMenuView.as_view(), name='manage_content'),

    # Add new modules, phrases and translations
    path('add_module', views.CreateModuleView.as_view(), name='add_module'),
    path('module/<int:pk>/add_phrase',
         views.CreatePhraseView.as_view(), name='add_phrase'),
    path('module/<int:pk1>/phrase/<int:pk2>/add_translation',
         views.CreateTranslationView.as_view(), name='add_translation'),

    # Edit modules, phrases and translations
    path('edit_module/<int:pk>', views.UpdateModuleView.as_view(), name='edit_module'),
    path('edit_phrase/<int:pk>', views.UpdatePhraseView.as_view(), name='edit_phrase'),
    path('edit_translation/<int:pk>',
         views.UpdateTranslationView.as_view(),name='edit_translation'),

    # Mass add / update modules, phrases and translations from CSV to DB
    path('csv_db_test', views.CsvToDbTestView.as_view(), name='csv_db_test'),
    path('csv_db_update', views.CsvToDbUpdateView.as_view(), name='csv_db_update'),

]

tommy/urls.py
from django.urls import path
from . import views

app_name = 'tommy'
urlpatterns = [
    # Home page
    path('', views.Home.as_view(), name='home'),

    # Profile creation and edit views
    path('create_profile', views.ProfileCreateView.as_view(), name='create_profile'),

    # Recalculate user phrase strength after each login
    path('reset/', views.ResetView.as_view(), name='reset'),

    # Dictionary view
    path('glossary', views.GlossaryView.as_view(), name='glossary'),

    # Modules view
    path('modules', views.ModulesView.as_view(), name='modules'),

    # Learn new phrases
    path('learn/<int:pk>', views.LearnView.as_view(), name='learn'),

    # Practice weakest phrases
    path('practice',views.PracticeView.as_view(), name='practice'),

    # Review phrases not seen for longes time
    path('review', views.ReviewView.as_view(), name='review'),

    # Practice correct accent translations
    path('accent', views.AccentView.as_view(), name='accent'),

    # Feedback page for practice, review and accent practice views
    path('feedback', views.FeedbackView.as_view(), name='feedback'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

home/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Tommy{% endblock title %}</title>

        <meta name="viewport" content="initial-scale=1, width=device-width">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">
        <link rel="stylesheet" href="{% static 'css/main.css' %}"
        
        {% block head %}{% endblock head %}
    </head>

    <body style="user-select: none"> 
        {% comment %} Move above style to style.css {% endcomment %}
        
        <div class="container">

            {% if user.is_authenticated and profile %}
                {% block navbar %}{% endblock navbar %}
            {% endif %}

            {% block nonav %}{% endblock nonav %}

            <header class="header p-3 mb-3 bg-light rounded-3 shadow-sm">
                <div class="container-fluid py-1 d-flex justify-content-between align-items-center">
                    {% block header %}{% endblock header %}
                </div>
            </header>


            <main class="main p-3 mb-3 bg-light rounded-3 shadow-sm">     
                {% block content %}{% endblock content %}
            </main>

            <div class="mt-3"></div>
            <footer class="footer p-3 mb-3 bg-light rounded-3 shadow-sm">
                <div class="container-fluid p-1 d-flex justify-content-around align-items-center">
                    
                    {% block footer %}{% endblock footer %}
                </div>
            </footer>
        
        </div>
        
    </body>
</html>

home/templates/base_menu.html
{% extends "base_bootstrap.html" %}

{% load app_tags %} <!-- see home/templatetags/app_tags.py -->

{% block navbar %}
<nav class="nav p-2 my-3 navbar navbar-expand-sm navbar-light bg-light rounded-3 shadow-sm">
    <div class="container-fluid">
        {% url 'tommy:home' as x %}
        <a class="navbar-brand link-style" href="{{ x }}">Home Menu</a>
        <ul class="navbar-nav container-fluid d-flex justify-content-around">
{% comment %} {% if request.get_full_path == x %}class="active"{% endif %} {% endcomment %}
        {% if user.is_staff %}
            <li>
                <a class="nav-link link-style" href="{% url 'staff:manage_content' %}" role="button">
                    Manage Content</a>
            </li>
        {% endif %}
            <li>
                <a class="nav-link link-style" href="{% url 'tommy:glossary' %}" role="button">
                    Browse Glossary</a>
            </li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class"nav-link link-style dropdown-toggle" href="#" id="rightnavDropdown" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    <img id="gravatar" class="rounded-3"
                        src="{{ user|gravatar:60}}" /><strong class="caret"></strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="rightnavDropdown">
                    <li><a class="dropdown-item link-style" href="{% url 'logout' %}?next={{ x }}">
                        Logout</a></li>
                </ul>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link link-style" href="{% url 'login' %}?next={{ x }}">Login</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>
{% endblock navbar %}