mysite/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve


urlpatterns = [
    path('', include('tommy.urls')),
    path('staff/', include('staff.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static')
    }),
]

# Configure admin page titles
admin.site.site_header = "Tommy Lanaguage App Admin"

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    # Main page for content admins to navigate adding and editing content
    path('', views.StaffMenuView.as_view(), name='manage_content'),

    # Add new modules, phrases and translations
    path('add_module', views.CreateModuleView.as_view(), name='add_module'),
    path('module/<int:pk>/add_phrase',
         views.CreatePhraseView.as_view(), name='add_phrase'),
    path('module/<int:pk1>/phrase/<int:pk2>/add_translation',
         views.CreateTranslationView.as_view(), name='add_translation'),

    # Edit modules, phrases and translations
    path('edit_module/<int:pk>', views.UpdateModuleView.as_view(), name='edit_module'),
    path('edit_phrase/<int:pk>', views.UpdatePhraseView.as_view(), name='edit_phrase'),
    path('edit_translation/<int:pk>',
         views.UpdateTranslationView.as_view(),name='edit_translation'),

    # Mass add / update modules, phrases and translations from CSV to DB
    path('csv_db_test', views.CsvToDbTestView.as_view(), name='csv_db_test'),
    path('csv_db_update', views.CsvToDbUpdateView.as_view(), name='csv_db_update'),

]

tommy/urls.py
from django.urls import path
from . import views

app_name = 'tommy'
urlpatterns = [
    # Home page
    path('', views.Home.as_view(), name='home'),

    # Profile creation and edit views
    path('create_profile', views.ProfileCreateView.as_view(), name='create_profile'),

    # Recalculate user phrase strength after each login
    path('reset/', views.ResetView.as_view(), name='reset'),

    # Dictionary view
    path('glossary', views.GlossaryView.as_view(), name='glossary'),

    # Modules view
    path('modules', views.ModulesView.as_view(), name='modules'),

    # Learn new phrases
    path('learn/<int:pk>', views.LearnView.as_view(), name='learn'),

    # Practice weakest phrases
    path('practice',views.PracticeView.as_view(), name='practice'),

    # Review phrases not seen for longes time
    path('review', views.ReviewView.as_view(), name='review'),

    # Practice correct accent translations
    path('accent', views.AccentView.as_view(), name='accent'),

    # Feedback page for practice, review and accent practice views
    path('feedback', views.FeedbackView.as_view(), name='feedback'),
]

home/models.py
from django.db import models

# Create your models here.

tommy/forms.py
from django import forms

from .models import Profile, UserPhraseStrength


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name']
    
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = "First name "


class PhraseStrengthForm(forms.ModelForm):
    class Meta:
        model = UserPhraseStrength
        fields = []


class TestForm(forms.Form):
    answer = forms.CharField(
        required=True,
        max_length=248,
        min_length=1,
        strip=True,
        label='',
        widget=forms.TextInput(
            attrs={
                'autofocus': True,
                'autocomplete': 'off',
                'placeholder': ' ...',
                'style': 'height: 5vh; font-size: x-large;'
        }))

home/views.py
from django.shortcuts import render

# Create your views here.

tommy/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, UpdateView, View, CreateView, ListView

from datetime import datetime
import html
from random import choice
from unidecode import unidecode
import string

from .models import Module, Phrase, Translation, Profile, UserPhraseStrength
from .forms import ProfileForm, TestForm

# Constants for setting user phrase view counts, evaluating accuracy and errors in testing views.
INITIATE_COUNT, UNASSESSED_ACCURACY, UNASSESSED_SCORE, MAX_ERRORS = 1, False, -1, 100


def eval_word(user_answer_word, correct_word):
    """
    Evaluates the test score for a word entered by the user in comparison to correct
    answer. Supports eval_tranlation function to evaluate translation accuracy.
    """
    # Variables to help evaluate word score
    correct_count, error_count = 0, 0
    answer_length, actual_length = len(user_answer_word), len(correct_word)

    # Case: user answer word is one char shorter than correct word
    if answer_length == actual_length - 1:
        words = []
        for i in range(actual_length):
            word = ""
            for j in range(actual_length):
                if i == j:
                    continue
                else:
                    word += correct_word[j]
            words.append(word)
        if user_answer_word in words:
            accuracy = ( ( actual_length - 1 ) / actual_length ) * 100
            return accuracy, 1
        
    # Case: user answer word is one char longer than correct word
    elif answer_length - 1 == actual_length:
        words = []
        for i in range(answer_length):
            word = ""
            for j in range(answer_length):
                if i == j:
                    continue
                else:
                    word += user_answer_word[j]
            words.append(word)
        if correct_word in words:
            accuracy = ( ( actual_length - 1 ) / actual_length ) * 100
            return accuracy, 1
    
    # Case: same length or more than one char longer or shorter
    shorter_word_length = min(actual_length, answer_length)
    for i in range(shorter_word_length):
        if correct_word[i] == user_answer_word[i]:
            correct_count += 1
        else:
            error_count += 1

    # Calculate score based on length difference and accuracy
    length_difference = abs(answer_length - actual_length)
    error_count += length_difference
    accuracy = ( correct_count / ( shorter_word_length + length_difference ) ) * 100
    return accuracy, error_count


def eval_tranlation(user_answer, correct_translation):
    """
    Evaluates the test score for a translation entered by the user
    in comparison to correct translation.
    """
    # Set variables to help evaluate accuracty of translation
    answer_str = user_answer.lower().translate(str.maketrans("", "", string.punctuation))
    correct_str = correct_translation.lower().translate(str.maketrans("", "", string.punctuation))
    answer_words, correct_words = answer_str.split(), correct_str.split()
    answer_str, correct_str = answer_str.replace(" ", ""), correct_str.replace(" ", "")
    actual_word_count, answer_word_count = len(correct_words), len(answer_words)
    actual_str_len, answer_str_len = len(correct_str), len(answer_str)
    error_count, total_score, FULL_SCORE, FAIL = 0, 0, 100, 0

    # Case: Exact same string gets fullscore
    if answer_str == correct_str:
        return FULL_SCORE, error_count
    
    # One word translation is evaluated for spelling errors and superfluous words
    elif actual_word_count == 1:
        if answer_word_count == 1:
            return eval_word(user_answer, correct_translation)
        else:
            factor = 1.7 / answer_word_count
            for word in answer_words:
                word_accuracy, word_errors = eval_word(word, correct_translation)
                if word_accuracy == FULL_SCORE:
                    error_count = word_errors + ( answer_str_len - ( actual_str_len - len(word) ) )
                    return word_accuracy * factor, error_count
            return FAIL, answer_str_len

    # Multiple word translation evaluates accuracy of words separately
    else:
        # If the number of words is the same compare the words one by one
        if answer_word_count == actual_word_count:
            for i in range(actual_word_count):
                if answer_words[i] == correct_words[i]:
                    total_score += FULL_SCORE
                else:
                    word_score, word_errors = eval_word(answer_words[i], correct_words[i])
                    total_score += word_score
                    error_count += word_errors
            return (total_score / actual_word_count), error_count
        # Otherwise search for the words in the full string
        else:
            if correct_str in answer_str or answer_str in correct_str:
                accuracy = ( ( actual_str_len - abs( actual_str_len - answer_str_len ) )
                            / actual_str_len * FULL_SCORE )
                accuracy = accuracy if accuracy > FAIL else FAIL
                error_count += abs(actual_str_len - answer_str_len)
                return accuracy, error_count
            else:
                factor = ( ( actual_word_count - abs( answer_word_count - actual_word_count ) )
                          / actual_word_count )
                correct_word_count = 0
                # TODO - This error count is not ideal and can be improved
                for word in correct_words:
                    if word in answer_words:
                        correct_word_count += 1
                    else:
                        error_count += int(len(word) / 2)
                for word in answer_words:
                    if word not in correct_words:
                        error_count += int(len(word) / 2)
                accuracy = (correct_word_count / actual_word_count) * factor * FULL_SCORE
                return accuracy, error_count


def feedback(user_answer, correct_translation, errors, score):
    """
    Generates HTML style tags to provide better feedback on translation accuracy.
    Used for learn, practice and review exercise view classes.
    """
    error_limit = len(correct_translation) / 8

    # Case: no errors
    if not errors or score == 100:
        return f'<span class="text-success">{user_answer}</span>'

    # Case: too many errors
    elif errors > error_limit or score < 70:
        return f'<span class="text-danger">{user_answer}</span>'
    
    # Set variables that help identify errors to mark for feedback
    else:
        actual_str = correct_translation.lower().translate(str.maketrans("", "", string.punctuation))
        answer_words, actual_words = user_answer.split(), unidecode(actual_str).split()
        answer_word_count, actual_word_count = len(answer_words), len(actual_words)
        user_answer_len = len(user_answer)
        html = '<span class="text-success">'
    
        # Case: one error and user answer same length as correct answer
        if errors == 1 and user_answer_len == len(correct_translation):
            for i in range(user_answer_len):
                if unidecode(user_answer[i].lower()) != unidecode(correct_translation[i].lower()):
                    html += f'<span class="text-danger">{user_answer[i]}</span>'
                else:
                    html += user_answer[i]
        else:
            # Case: user answer is longer than correct answer
            if answer_word_count >= actual_word_count:
                for word in answer_words:
                    check_word = unidecode(
                        word.lower().translate(str.maketrans("", "", string.punctuation))
                    )
                    if check_word not in actual_words:
                        html += f'<span class="text-danger">{word}</span> '
                    else:
                        html += f'{word} '
                        actual_words.remove(check_word)
            # Case user answer is short or equal in lengh to correct answer
            else:
                for i in range(answer_word_count):
                    if actual_words[i] != unidecode(
                        answer_words[i].translate(str.maketrans("", "", string.punctuation))
                    ):
                        html += f'<span class="text-danger">{answer_words[i]}</span> '
                    else:
                        html += f'{answer_words[i]} '
        return html + '\b</span>'


def accent_feedback(user_answer, correct_translation, errors, score):
    """
    Generates HTML style tags to provide better feedback on translation
    accuracy. Used in the accent testing extreme difficulty excercise view.
    """
    # Set variables to help identify errors to mark for feedback
    answer_str = user_answer.translate(str.maketrans("", "", string.punctuation))
    actual_str = correct_translation.translate(str.maketrans("", "", string.punctuation))
    error_limit = len(correct_translation) / 8

    # Case: user answer is exact same as correct answer
    if (not errors or score == 100) and answer_str == actual_str:
        return f'<span class="text-success">{user_answer}</span>'
    
    # Case: too many errors
    elif errors > error_limit or score < 70:
        return f'<span class="text-danger">{user_answer}</span>'

    # Remaining variables for checking errors to help generate feedback
    else:
        answer_words, actual_words = answer_str.split(), actual_str.split()
        ans_feedback, html = user_answer.split(), '<span class="text-success">'
        answer_words = [answer_words] if isinstance(answer_words, str) else answer_words
        actual_words = [actual_words] if isinstance(actual_words, str) else actual_words

tommy/templates/tommy/accent.html
{% extends "base_bootstrap.html" %}
{% load humanize %}

{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder">{{ profile.name }}</p>
        <p class="text-end p-2 fs-4">
            <span class="badge bg-success px-3">
            XP {{ profile.xp|intcomma }}</span></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<div class="container-fluid d-flex justify-content-between">
    <p class="text-start p-3 fs-3">
        {% if phrase.language == "French" %}
        Translate from French to English
        {% else %}
        Translate from English to French
        {% endif %}
    </p>
</div>
{% endblock header %}


{% block content %}
<div class="container-fluid p-4 d-flex justify-content-between">  
    {% if not phrase %}
    <p>Learn phrases before doing practice</p>
    {% else %}
        <p class="fs-3 ps-5 lh-sm">
            <span class="fs-6 text-muted"></span><br>
            {{ phrase }}</p>
    {% endif %}
</div>
{% endblock content %}


{% block footer %}
    <div class="container px-5 lh-sm">
        {% if message %}
            <p class="text-danger fs-5 mt-3"><strong>{{ message }}<strong></p>
        {% endif %}
        {% load crispy_forms_tags %}
        <form action="" method="post" id="upload_form" enctype="multipart/form-data">
            <span class="fs-6 text-muted"></span><br>
            {% if form.errors %}
                <p>There was an error. Please try again.</p>
            {% endif %}
            {% csrf_token %}
            {{ form|crispy }}
        </form>
    </div>
{% endblock footer %}

tommy/templates/tommy/create_profile.html
{% extends "base_menu.html" %}

{% block nonav %}
<div class="nav p-2 my-3 navbar navbar-expand-sm navbar-light bg-light rounded-3 shadow-sm">
    <div class="container-fluid">
        <p> </p>
    </div>
</div>
{% endblock nonav %}


{% block header %}
    <h1 class="display-3 text-muted pt-3">Set up your profile</h1>   
{% endblock header %}


{% block content %}
    <div class="container p-3">
        {% load crispy_forms_tags %}
        <form action="" method="post" id="upload_form" enctype="multipart/form-data">
            {% if form.errors %}
                <p>There was an error with your form. Please try again.</p>
            {% endif %}
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit &raquo;" class="btn btn-lg btn-success">
        </form>
    </div>

{% endblock content %}

tommy/templates/tommy/feedback.html
{% extends "base_bootstrap.html" %}
{% load humanize %}

{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder">{{ profile.name }}</p>
        {% if module_progress %}
            <div style="width:39%" class="pb-2">
                <label for="prog-bar">Module progress (Module: {{ module_name }})</label>
                <div class="progress" id="prog-bar" style="width: 100%; height: 25px;">
                    <div class="progress-bar progress-bar-striped bg-danger fw-bold fs-6"
                        role="progressbar" style="width: {{ module_progress }}%;"
                        aria-valuenow="{{ module_progress }}" aria-valuemin="0" aria-valuemax="100">
                        {{ module_progress }}%</div>
            </div></div>
        {% endif %}
        <p class="text-end p-2 fs-4">
            <span class="badge bg-success px-3">
            XP {{ profile.xp|intcomma }}</span></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<div class="container-fluid d-flex justify-content-between">
    <p class="p-3 fs-3">
        {{ result }} 
    </p>
</div>
{% endblock header %}


{% block content %}
<div class="row p-4 container-fluid d-flex justify content between">
    {% if not phrase %}
    Error with feedback on testing phrase
    {% else %}
        <div class="ps-4 col-5 text-start">   
            <p class="fs-6 text-muted mb-1">Test phrase ({{ phrase.language }})</p>
            <p class="fs-3 lh-sm">{{ phrase }}</p>
        </div>
        <div class="ps-5 col-7 text-start">
            <p class="fs-6 text-muted mb-0">
                {% if translations|length == 1 %}
                Translation{% else %}
                Translations{% endif %} ({{ translations.0.language }})</p>
            {% for translation in translations %}
                <p class="fs-4 lh-sm mb-1">{{ translation.translation }}&nbsp;</p>
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock content %}


{% block footer %}
<div class="row ps-4 container-fluid d-flex justify content between">
    <div class="col-6">
        <p class="fs-3 lh-sm text-dark text-start">
            <span class="fs-6 text-muted">Your answer</span><br>
                <span class="fw-bold">
            {% if feedback_html %}
                {{ feedback_html|safe }}
            {% else %}
                {% if response_accuracy == True %}
                    <span class="text-success fw-bold">{{ user_answer }}
                {% else %}
                    <span class="text-danger fw-bold">{{ user_answer }}
                {% endif %}
            {% endif %}
        </span></p>
    </div>
    <div class="col-2">
        <p class="text-success pt-4 fs-2 fw-bold">
            {% if response_accuracy == True %}
            +5 XP
            {% endif %}
        </p>
    </div>
    <div class="col-4 text-end">
        {% if testing_view == 'tommy:learn' %}
            <p><a href="{% url testing_view module_id %}" autofocus
                class="btn btn-lg btn-primary mt-3">Next test question</a></p>
        {% else %}
            <p><a href="{% url testing_view %}" autofocus
                class="btn btn-lg btn-primary mt-3">Next test question</a></p>
        {% endif %}
        </div>
</div>
{% endblock footer %}

tommy/templates/tommy/glossary.html
{% extends "base_menu.html" %}
{% load humanize %}


{% block header %}
    {% if profile %}    
    <div class="container-fluid d-flex justify-content-between">
        <p class="fs-4 fw-bolder">{{ profile.name }}</p>
        <div style="width:39%" class="pb-2">
            <label for="prog-bar">Course progress</label>
            <div class="progress" id="prog-bar" style="width: 100%; height: 25px;">
                <div class="progress-bar progress-bar-striped bg-danger fw-bold fs-6"
                    role="progressbar" style="width: {{ progress }}%;"
                    aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">
                    {{ progress }}%</div>
        </div></div>
        <p class="text-end fs-4">
            <span class="badge bg-success fw-bold px-3">
                XP {{ profile.xp|intcomma }}</span></p>
    </div>
    {% endif %}
{% endblock header %}


{% block content %}
<section class="container-fluid d-flex justify-content-between">
    <form action="" muted="get" class="m-4 input-group">
        <input type="text" placeholder="Search phrases and translations" name="search"
        class="form-control"
        {% if search %} value="{{ search }}" {% endif %}>
        <button type="submit" class="btn btn-outline-dark">
            <i class="fa fa-search"></i></button>
        <a href="{% url 'tommy:glossary' %}" class="btn btn-outline-dark">
            <i class="fa fa-undo pt-1"></i></a>
    </form>
</section>

<section class="container-fluid p-2">
    <div class="container">
        <div class="row pb-2">
            <div class="col-4 text-end fw-bold">Phrase</div>
            <div class="col-5 text-start fw-bold">Translation</div>
            <div class="col-3 text-end fw-bold">Strength</div>
        </div>
    </div>
    
    <div class="container card" id="container-card">
        {% if not phrase_data and search %}
        <div class="row justify-content-center p-5 fs-5">
            Your search found no phrases for "{{ search }}"
        </div>
        {% else %}
        
        {% if phrase_data %}{% for phrase in phrase_data %}{% if phrase.language == "French" %}
        <div class="row pb-3">
            <div class="col-4 text-end">{{ phrase.phrase }} </div>
            <div class="col-5 text-start">
                {% for translation in phrase.translations %}
                    &raquo; {{ translation }} <br>
                {% endfor %}
            </div>
            <div class="col-3 text-end">
                {% if phrase.learned %}
                    {% if phrase.strength > 90 %}Excellent
                    {% elif phrase.strength > 80 %}Amazing
                    {% elif phrase.strength > 60 %}Great
                    {% elif phrase.strength > 40 %}Good
                    {% else %}Keep at it {% endif %}
                {% else %}
                    <a href="{% url 'tommy:learn' phrase.module_id %}"
                        class="text-decoration-none link-style">Learn in Module: {{ phrase.module }}</a>
                {% endif %}
            </div>
        </div>
        {% endif %}{% endfor %}{% endif %}   
    </div>
</section>
    {% endif %}
{% endblock content %}


{% block footer %}
<div class="container p-4 fs-5">
    {% if strength_data.learned > 0 %}
        <p>You learned to translate {{ strength_data.learned }} French and English phrases and 
            achieved an average score of {{ strength_data.average }}%.</p>
    {% else %}
            <p>Start learning. Choose a module above or click on Learn in the Home Menu.</p>
    {% endif %}
</div>
{% endblock footer %}

tommy/templates/tommy/home.html
{% extends "base_menu.html" %}
{% load humanize %}


{% block header %}
    {% if profile %}    
    <div class="container-fluid d-flex justify-content-between">
        <p class="fs-4 fw-bolder">{{ profile.name }}</p>
        <div style="width:39%" class="pb-2">
            <label for="prog-bar">Course progress</label>
            <div class="progress" id="prog-bar" style="width: 100%; height: 25px;">
                <div class="progress-bar progress-bar-striped bg-danger fw-bold fs-6"
                    role="progressbar" style="width: {{ progress }}%;"
                    aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">
                    {{ progress }}%</div>
        </div></div>
        <p class="text-end fs-4">
            <span class="badge bg-success fw-bold px-3">
                XP {{ profile.xp|intcomma }}</span></p>
    </div>
    {% endif %}
{% endblock header %}


{% block content %} 
<div class="p-3">
    <h1 class="fs-3">Activities</h1>
    {% comment %} {% if unlearned_phrase_count == 0 %}
    <p>Choose an activity to practice what you've learned.</p>
    {% else%}
    <p>Choose an activity to learn new phrases or review past content.</p>
    {% endif %} {% endcomment %}
</div>
<div class="container-fluid p-3 d-flex flex-wrap justify-content-evenly align-items-center">
    {% if user.is_authenticated and not profile %}
        Welcome, {{ user.username }}.
        <br>Click the button to complete your profile.
        <a href="{% url 'tommy:create_profile' %}"
            class="btn btn-lg btn-primary m-3 p-3 fs-4">
            Complete profile &raquo;</a>
  
    {% else %}
    {% if unlearned_phrase_count > 0 %}
        <p><a href="{% url 'tommy:modules' %}" alt="Learn new expressions"
            class="btn btn-lg btn-outline-primary mx-4 my-3 fs-4">
            <span title="Learn new expressions">Learn &#x1F4DA;</span></a></p>
    {% endif %}
        {% if learned_phrase_count > 0 %}
        <p><a href="{% url 'tommy:practice' %}" alt="Strengthen weakest phrases"
            class="btn btn-lg btn-outline-primary mx-4 my-3 fs-4">
            <span title="Strengthen weakest phrases">Practice &#x1F4AF;</span></a></p>
        <p><a href="{% url 'tommy:review' %}" alt="Review what you've learned"
            class="btn btn-lg btn-outline-primary mx-4 my-3 fs-4">
            <span title="Review what you've learned">Review &#x1F4AD;</span></a></p>
        <p><a href="{% url 'tommy:accent' %}"  alt="Use correct French accents"
            class="btn btn-lg btn-outline-primary mx-4 my-3 fs-4">
            <span title="Use correct French accents">Extreme &#x1F92F;</span></a></p>
    {% endif %}
        <p><a href="{% url 'tommy:glossary' %}" alt="Browse phrases and translations"
            class="btn btn-lg btn-outline-primary mx-4 my-3 fs-4">
            <span title="Browse phrases and translations">Study &#x1F4D1;</span></a></p>
    {% endif %}
</div>
{% endblock content %}


{% block footer %}
<div class="container p-5">
    <p> </p>
</div>
{% endblock footer %}

tommy/templates/tommy/learn.html
{% extends "base_bootstrap.html" %}
{% load humanize %}

{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder">{{ profile.name }}</p>
        <div style="width:39%" class="pb-2">
            <label for="prog-bar">Module progress (Module: {{ module_name }})</label>
            <div class="progress" id="prog-bar" style="width: 100%; height: 25px;">
                <div class="progress-bar progress-bar-striped bg-danger fw-bold fs-6"
                    role="progressbar" style="width: {{ module_progress }}%;"
                    aria-valuenow="{{ module_progress }}" aria-valuemin="0" aria-valuemax="100">
                    {{ module_progress }}%</div>
        </div></div>
        <p class="text-end p-2 fs-4">
            <span class="badge bg-success px-3">
            XP {{ profile.xp|intcomma }}</span></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<div class="container-fluid d-flex justify-content-between">
    <p class="text-start p-3 fs-3">
        {% if phrase.language == "French" %}
        Translate from French to English
        {% else %}
        Translate from English to French
        {% endif %}
    </p>
</div>
{% endblock header %}


{% block content %}
<div class="container-fluid p-3 d-flex justify-content-between">  
    {% if not phrase %}
    <p>Learn phrases before doing practice</p>
    {% else %}
        <p class="fs-3 ps-5 lh-sm">
            <span class="fs-6 text-muted"></span><br>
            {{ phrase }}</p>
    {% endif %}
</div>
{% endblock content %}


{% block footer %}
    <div class="container px-5 lh-sm">
        {% if message %}
            <p class="text-danger fs-5 mt-3"><strong>{{ message }}<strong></p>
        {% endif %}
        {% load crispy_forms_tags %}
        <form action="" method="post" id="upload_form" enctype="multipart/form-data">
            <span class="fs-6 text-muted"></span><br>
            {% if form.errors %}
                <p>There was an error. Please try again.</p>
            {% endif %}
            {% csrf_token %}
            {{ form|crispy }}
        </form>
    </div>

{% endblock footer %}

tommy/templates/tommy/modules.html
{% extends "base_menu.html" %}
{% load humanize %}

{% block header %}
    {% if profile %}    
    <div class="container-fluid d-flex justify-content-between">
        <p class="fs-4 fw-bolder">{{ profile.name }}</p>
        {% if module_complete_msg %}
            <p class="text-primary fs-4 text-center" style="width:50%">
                <strong>{{ module_complete_msg }}<strong></p>
        {% else %}
            <div style="width:39%" class="pb-2">
                <label for="prog-bar">Course progress</label>
                <div class="progress" id="prog-bar" style="width: 100%; height: 25px;">
                    <div class="progress-bar progress-bar-striped bg-danger fw-bold fs-6"
                        role="progressbar" style="width: {{ progress }}%;"
                        aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">
                        {{ progress }}%</div>
            </div></div>
        {% endif %}
        <p class="text-end fs-4">
            <span class="badge bg-success fw-bold px-3">
                XP {{ profile.xp|intcomma }}</span></p>
    </div>
    {% endif %}
{% endblock header %}


{% block content %} 
<div class="container-fluid p-3 d-flex flex-wrap justify-content-evenly align-items-center">
    {% for module in modules %}
    {% for open_module in open_modules %}{% if open_module == module %}
    <p class="mx-5 my-3"><a href="{% url 'tommy:learn' module.id %}"
        class="btn btn-lg btn-outline-primary">{{ module.name }}</a></p>
    {% endif %}{% endfor %}
    {% for closed_module in closed_modules %}{% if closed_module == module %}
    <p class="btn btn-lg btn-outline-secondary text-dark disabled mx-5 my-3">
        {{ module.name }}</p>
    {% endif %}{% endfor %}
    {% endfor %}
</div>
{% endblock content %}


{% block footer %}{% endblock footer %}

tommy/templates/tommy/reset.html
{% extends "base_bootstrap.html" %}

{% block nonav %}

{% endblock nonav %}


{% block header %}

{% endblock header %}


{% block content %}
    <form id="resetForm" method="post" action="{% url 'tommy:reset' %}">
        {% csrf_token %}
        <input type="hidden" name="reset" value="reset">
    </form>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('resetForm').submit();
        })
    </script>
{% endblock content %}


{% block footer %}

{% endblock footer %}