mysite/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve


urlpatterns = [
    path('', include('tommy.urls')),
    path('staff/', include('staff.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static')
    }),
]

# Configure admin page titles
admin.site.site_header = "Tommy Lanaguage App Admin"

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'
urlpatterns = [
    # Main page for content admins to navigate adding and editing content
    path('', views.StaffMenuView.as_view(), name='manage_content'),

    # Add new modules, phrases and translations
    path('add_module', views.CreateModuleView.as_view(), name='add_module'),
    path('module/<int:pk>/add_phrase',
         views.CreatePhraseView.as_view(), name='add_phrase'),
    path('module/<int:pk1>/phrase/<int:pk2>/add_translation',
         views.CreateTranslationView.as_view(), name='add_translation'),

    # Edit modules, phrases and translations
    path('edit_module/<int:pk>', views.UpdateModuleView.as_view(), name='edit_module'),
    path('edit_phrase/<int:pk>', views.UpdatePhraseView.as_view(), name='edit_phrase'),
    path('edit_translation/<int:pk>',
         views.UpdateTranslationView.as_view(),name='edit_translation'),

    # Mass add / update modules, phrases and translations from CSV to DB
    path('csv_db_test', views.CsvToDbTestView.as_view(), name='csv_db_test'),
    path('csv_db_update', views.CsvToDbUpdateView.as_view(), name='csv_db_update'),

]

staff/models.py
from django.db import models

# Create your models here.

tommy/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(
        max_length=25,
        validators=[MinLengthValidator(1, "Choose a name I can call you")]
    )
    xp = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def is_valid_profile(self):
        User = get_user_model()
        user_test = User.objects.filter(username=self.user.username).exists()
        return self.xp >= 0 and len(self.name) >= 1 and user_test

    def __str__(self):
        return f"{self.user.username}'s Profile"


class Module(models.Model):
    name = models.CharField(
        unique=True,
        max_length=24,
        validators=[MinLengthValidator(3, "This name is too short")]
    )

    def is_valid_module(self):
        return 3 <= len(self.name) <= 24

    def __str__(self):
        return self.name


class Phrase(models.Model):
    FRENCH = "French"
    ENGLISH = "English"
    LANGUAGES = [
        (FRENCH, "French"),
        (ENGLISH, "English")
    ]
    language = models.CharField(max_length=12, choices=LANGUAGES, default=FRENCH)
    phrase = models.CharField(
        max_length=248,
        validators=[MinLengthValidator(1, "This phrase is too short")]
    )
    phrase_strength = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='UserPhraseStrength')
    module = models.ForeignKey(Module, null=True, on_delete=models.SET_NULL,
        related_name='phrases_in_module')
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta: # Converted from unique_together to Meta.indexes - run: python -Wa manage.py test
        constraints = [ # models.functions.Lower('name'),
            models.UniqueConstraint(fields=['phrase', 'language'], name='unique_phrase_language')
        ]

    def is_valid_phrase(self):
        language_test = self.language in ["French", "English"]
        phrase_test = 1 <= len(self.phrase) <= 248
        module_test = Module.objects.filter(name=self.module.name).exists()
        module_name_test = (3 <= len(self.module.name) <= 24)
        return language_test and phrase_test and module_test and module_name_test

    def __str__(self):
        return self.phrase


class Translation(models.Model):
    FRENCH = "French"
    ENGLISH = "English"
    LANGUAGES = [
        (FRENCH, "French"),
        (ENGLISH, "English")
    ]
    language = models.CharField(max_length=12, choices=LANGUAGES, default=FRENCH)
    translation = models.CharField(
        max_length=248,
        validators=[MinLengthValidator(1, "This phrase is too short")]
    )
    phrase = models.ForeignKey(Phrase, null=True, on_delete=models.SET_NULL,
        related_name='phrase_translations')
    
    # For creation and update times, rely to phrase datetime data
    
    def is_valid_translation(self):
        valid_languages = ["French", "English"]
        translation_language_test = self.language in valid_languages
        phrase_language_test = self.phrase.language in valid_languages
        comparative_language_test = self.language != self.phrase.language
        translation_length_test = 1 <= len(self.translation) <= 248
        phrase_exists_test = Phrase.objects.filter(phrase=self.phrase.phrase).exists()
        phrase_length_test = 1 <= len(self.phrase.phrase) <= 248
        module_name_test = 3 <= len(self.phrase.module.name) <= 24
        return (translation_language_test and phrase_language_test
                and comparative_language_test and translation_length_test
                and phrase_exists_test and phrase_length_test and module_name_test)

    def __str__(self):
        return f'{self.translation} ({self.phrase})'


class UserPhraseStrength(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='user_phrase_strength')
    phrase = models.ForeignKey(Phrase, on_delete=models.CASCADE)
    learned = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    correct = models.IntegerField(default=0)
    strength = models.IntegerField(default=0)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'phrase'], name='unique_user_phrase_strength')
        ]
    
    def is_valid_user_phrase_strength(self):
        User = get_user_model()
        user_test = User.objects.filter(username=self.user.username).exists()
        phrase_test = Phrase.objects.filter(phrase=self.phrase.phrase).exists()
        phrase_length_test = 1 <= len(self.phrase.phrase) <= 248
        phrase_language_test = self.phrase.language in ["French", "English"]
        learned_test = self.learned in [True, False]
        views_count_test = self.views >= 0
        correct_count_test = self.correct >= 0
        strength_score_test = 0 <= self.strength <= 100
        return (user_test and phrase_test and phrase_length_test and learned_test
                and views_count_test and correct_count_test and strength_score_test
                and phrase_language_test)

    def __str__(self):
        return f'{self.user.username}  "{self.phrase.phrase}"'

staff/views.py
from csv import reader, DictWriter
from datetime import datetime
from json import loads
from re import match

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView, View

from tommy.models import Module, Phrase, Translation, Profile, UserPhraseStrength

from .forms import ModuleForm, CreatePhraseForm, CreateTranslationForm, UpdatePhraseForm, UpdateTranslationForm, CsvTestForm, CsvSubmitForm
    

class StaffMenuView(LoginRequiredMixin, ListView):
    """Admin staff menu to navigate adding and editing content."""

    template_name = 'staff/manage_content.html'
    
    def get(self, request):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        profile = Profile.objects.get(user=request.user)
        modules = Module.objects.all().order_by('name')
        phrases = Phrase.objects.all().order_by('phrase')
        translations = Translation.objects.all().order_by('translation')

        context = {
            'profile': profile,
            'modules': modules,
            'phrases': phrases,
            'translations': translations,
        }
        
        return render(request, self.template_name, context)


# Three views for adding new content
class CreateModuleView(PermissionRequiredMixin, CreateView):
    """Admin page. Adds new modules to the database."""

    permission_required = 'tommy.add_module'
    template_name = 'staff/add_module.html'
    
    def get(self, request):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        form = ModuleForm()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        form = ModuleForm(request.POST)

        if not form.is_valid():
            context = {'form': form}
            return render(request, self.template_name, context)
        
        # Save new module and redirect to add phrases to this module
        module = form.save()
        success_url = reverse_lazy('staff:add_phrase', kwargs={'pk': module.id})
        return redirect(success_url)


class CreatePhraseView(PermissionRequiredMixin, CreateView):
    """Admin page. Adds new phrases to the database."""

    permission_required = 'tommy.add_phrase'
    template_name = 'staff/add_phrase.html'
    
    def get(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)

        module = Module.objects.get(id=pk)
        phrases = Phrase.objects.filter(module=module)
        form = CreatePhraseForm()
        context = {'form': form, 'module': module, 'phrases': phrases}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        form = CreatePhraseForm(request.POST)
        module = Module.objects.get(id=pk)

        if not form.is_valid():
            context = {'form': form, 'module': module}
            return render(request, self.template_name, context)
        
        # Save new phrase after setting its module
        phrase = form.save(commit=False)
        phrase.module = module
        phrase.save()

        # Create a phrase strength object for the new phrase for every user 
        User = get_user_model()
        users = User.objects.all()
        for user in users:
            UserPhraseStrength.objects.create(
                phrase = phrase,
                user = user,
                learned = False,
                strength = 0,
                views = 0,
                correct = 0
            )
            
        success_url = reverse_lazy('staff:add_phrase', kwargs={'pk': pk})
        return redirect(success_url)


class CreateTranslationView(PermissionRequiredMixin, CreateView):
    """Admin page. Adds new phrase translations to the database."""

    permission_required = 'tommy.add_translation'
    template_name = 'staff/add_translation.html'
    
    def get(self, request, pk1, pk2):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        module = Module.objects.get(id=pk1)
        phrase_set = Phrase.objects.filter(module=module)
        current_phrase = Phrase.objects.get(id=pk2)
        translations = Translation.objects.filter(phrase=current_phrase)
        form = CreateTranslationForm()
        context = {
            'form': form,
            'module': module,
            'current_phrase': current_phrase,
            'phrase_set': phrase_set,
            'translations': translations
        }
        return render(request, self.template_name, context)
    
    def post(self, request, pk1, pk2):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        form = CreateTranslationForm(request.POST)
        phrase = Phrase.objects.get(id=pk2)

        if not form.is_valid():
            module = Module.objects.get(id=pk1)
            phrase_set = Phrase.objects.filter(module=module)
            translations = Translation.objects.filter(phrase=phrase)
            
            context = {
                'form': form,
                'module': module,
                'current_phrase': phrase,
                'phrase_set': phrase_set,
                'translations': translations
            }
            return render(request, self.template_name, context)

        translation = form.save(commit=False)
        translation.phrase = phrase
        translation.save()

        success_url = reverse_lazy(
            'staff:add_translation', kwargs={'pk1': pk1, 'pk2': pk2}
        )
        return redirect(success_url)


# Three views for editing content
class UpdateModuleView(PermissionRequiredMixin, UpdateView):
    """Admin page. Edits modules in the database."""

    permission_required = 'tommy.change_module'
    template_name = 'staff/edit_module.html'
    
    def get(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        module = Module.objects.get(id=pk)
        form = ModuleForm(instance=module)
        context = {'module': module, 'form': form}
        return render(request, self.template_name, context)
    
    def post(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        module = get_object_or_404(Module, id=pk)
        form = ModuleForm(request.POST, instance=module)

        if not form.is_valid():
            context = {'module': module, 'form': form}
            return render(request, self.template_name, context)

        form.save()
        success_url = reverse_lazy('staff:manage_content')
        return redirect(success_url)


class UpdatePhraseView(PermissionRequiredMixin, UpdateView):
    """Admin page. Edits phrases in the database."""

    permission_required = 'tommy.change_phrase'
    template_name = 'staff/edit_phrase.html'
    
    def get(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        phrase = Phrase.objects.get(id=pk)
        form = UpdatePhraseForm(instance=phrase)
        module = Module.objects.get(name=phrase.module)
        context = {'form': form, 'module': module, 'phrase': phrase}
        return render(request, self.template_name, context)
    
    def post(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        phrase = get_object_or_404(Phrase, id=pk)
        form = UpdatePhraseForm(request.POST, instance=phrase)

        if not form.is_valid():
            module = Module.objects.get(name=phrase.module)
            context = {'form': form, 'module': module, 'phrase': phrase}
            return render(request, self.template_name, context)

        form.save()
        success_url = reverse_lazy('staff:manage_content')
        return redirect(success_url)


class UpdateTranslationView(PermissionRequiredMixin, UpdateView):
    """Admin page. Edits phrase translations in the database."""

    permission_required = 'tommy.change_translation'
    template_name = 'staff/edit_translation.html'
    
    def get(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
    
        translation = Translation.objects.get(id=pk)
        form = UpdateTranslationForm(instance=translation)
        phrase = Phrase.objects.get(phrase=translation.phrase)
        module = Module.objects.get(name=phrase.module)
        context = {
            'form': form,
            'module': module,
            'phrase': phrase,
            'translation': translation
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        if not request.user.is_staff:
            non_staff_url = 'tommy:home'
            return redirect(non_staff_url)
        
        translation = get_object_or_404(Translation, id=pk)
        form = UpdateTranslationForm(request.POST, instance=translation)
        if not form.is_valid():
            phrase = Phrase.objects.get(phrase=translation.phrase)

staff/templates/staff/add_module.html
{% extends "base_menu.html" %}


{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder"></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<h1 class="p-3 fs-2">
    <span class="text-muted">Add a new learning module for a phrase set</span>
</h1>
{% endblock header %}


{% block content %}
<div class="container-fluid p-3 row">
    <div class="col-9">
        <h4 class="py-3">Enter a name</h4>
        {% load crispy_forms_tags %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit"
                class="btn btn-outline-success me-3 text-dark">
            <input type="submit" value="Cancel &nbsp;&raquo;&nbsp; return to menu"
                class="btn btn-outline-danger text-dark"
                onclick="window.location.href='{% url 'staff:manage_content' %}';return false;">
        </form>
    </div>
</div>
{% endblock content %}


{% block footer %}
    
{% endblock footer %}

staff/templates/staff/add_phrase.html
{% extends "base_menu.html" %}


{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder"></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<h1 class="p-3 fs-2">
    <span class="text-muted">Add phrases to module</span> {{ module.name }}
</h1>
{% endblock header %}


{% block content %}
<div class="container-fluid p-3 row">
    <div class="col-6">
        {% if phrases %}
        <h5 class="text-muted">Phrases in this module</h5>
        <ul>
            {% for phrase in phrases %}
            <li>{{ phrase.phrase }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <h5  class="text-muted">
            No phrases yet in {{ module.name }}
        </h5>
        {% endif %}
        <h4 class="py-3">Add a new phrase</h4>
        {% load crispy_forms_tags %}
        <form action="" method="post" enctype="multipart/form-data"
            class="p-2">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit"
                class="btn btn-outline-success me-3 text-dark">
            <input type="submit" value="Cancel &nbsp;&raquo;&nbsp; return to menu"
                class="btn btn-outline-danger text-dark"
                onclick="window.location.href='{% url 'staff:manage_content' %}';return false;">
        </form>
    </div>
    <div class="col-6">
        {% if phrases %}
        <h4 class="text-muted pb-3">Enough phrases in this module?</h4>
        <h5 class="fs-5">Add translations to phrases in {{ module.name}} </h5>
        <p class="text-muted">Chooose a phrase</p>
        {% for phrase in phrases %}
        <a href="{% url 'staff:add_translation' module.id phrase.id %}"
            class="btn btn-outline-dark m-1">{{ phrase.phrase }}</a>
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock content %}


{% block footer %}

{% endblock footer %}

staff/templates/staff/add_translation.html
{% extends "base_menu.html" %}


{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder"></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<h1 class="p-3 fs-2">
    <span class="text-muted">Add translations to phrase</span> {{ current_phrase.phrase }}
    <span class="text-muted"> in module</span> {{ module.name}}
</h1>
{% endblock header %}


{% block content %}
<div class="container-fluid p-3 row">
    <div class="col-6">
        
        {% if translations %}
        <h5  class="text-muted">
            Translations to {{ current_phrase.phrase }}
        </h5>
        <ul>
            {% for translation in translations %}
            <li>{{ translation.translation }}</li>
            {% endfor %}
        </ul>
        {% else %}
        <h5  class="text-muted">
            No translations yet for {{ current_phrase.phrase }}
        </h5>
        {% endif %}
        <h4 class="py-3">Add a new translation to the phrase {{ current_phrase.phrase}} </h4>
        {% load crispy_forms_tags %}
        <form action="" method="post" enctype="multipart/form-data"
            class="p-2">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit"
                class="btn btn-outline-success me-3 text-dark">
            <input type="submit" value="Cancel &nbsp;&raquo;&nbsp; return to menu"
                class="btn btn-outline-danger text-dark"
                onclick="window.location.href='{% url 'staff:manage_content' %}';return false;">
        </form>
    </div>
    <div class="col-6">
        {% if phrase_set|length > 1 %}
        <h4 class="text-muted pb-3">Enough translations to this phrase?</h4>
        <h5 class="fs-5">Add translations to another phrase in {{ module.name}} </h5>
        <p class="text-muted">Chooose a phrase</p>
        {% for phrase in phrase_set %}{% if phrase != current_phrase %}
        <a href="{% url 'staff:add_translation' module.id phrase.id %}"
            class="btn btn-outline-dark m-1">{{ phrase.phrase }}</a>
            {% endif %}{% endfor %}    
        {% endif %}
    </div>
</div>
{% endblock content %}


{% block footer %}

{% endblock footer %}

staff/templates/staff/edit_module.html
{% extends "base_menu.html" %}


{% block nonav %}
<div class="nonav px-3 my-3 navbar rounded-3 shadow-sm">
    <div class="container-fluid">
        <p class="fs-4 ps-3 fw-bolder"></p> 
    </div>
</div>
{% endblock nonav %}


{% block header %}
<h1 class="p-3 fs-2">
    <span class="text-muted">Edit module</span> {{ module.name }}
</h1>
{% endblock header %}


{% block content %}
<div class="container-fluid p-3 row">
    <div class="col-9">
        <h4 class="py-3">Update field</h4>
        {% load crispy_forms_tags %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit"
                class="btn btn-outline-success me-3 text-dark">
            <input type="submit" value="Cancel &nbsp;&raquo;&nbsp; return to menu"
                class="btn btn-outline-danger text-dark"
                onclick="window.location.href='{% url 'staff:manage_content' %}';return false;">
        </form>
    </div>
</div>
{% endblock content %}


{% block footer %}
    
{% endblock footer %}

staff/templates/staff/manage_content.html
{% extends "base_menu.html" %}


{% block header %}
{% if user.is_staff %} 
<div class="container-fluid d-flex justify-content-between">
    <p class="fs-5 fw-bolder">App Content Admin</p>
    <p class="text-end fs-5">Staff profile: {{ profile.name }}</p>
</div>
{% endif %}
{% endblock header %}


{% block content %}
<div class="container-fluid">
    <div class="row p-3">
        <div class="col-6">
            <h5>Add modules</h5>
            <p class="w-100"><a href="{% url 'staff:add_module' %}"
                class="btn btn-lg btn-outline-dark w-100">
                Add new modules</a></p>
        </div>
        <div class="col-6">
            <h5>Edit modules</h5>
            <form id="edit_module_form" action="" method="get" class="input-group">
                <select id="edit_module" class="form-control" required>
                    <option disabled selected value>Select a module to edit</option>
                    {% if modules %}{% for module in modules %}
                    <option value="{{ module.id }}">{{ module.name }}</option>
                    {% endfor %}{% endif %}
                </select>
                <button type="submit" class="btn btn-lg btn-outline-dark"
                    id="edit_module_submit">Select</button>
            </form>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-6 pb-3">
            <h5>Add phrases <span class="text-muted">to modules</span></h5>
            <form id="add_phrase_form" action="" method="get" class="input-group">
                <select id="add_phrase" class="form-control" required>
                    <option disabled selected value>Select a module to add phrases</option>
                    {% if modules %}{% for module in modules %}
                    <option value="{{ module.id }}">{{ module.name }}</option>
                    {% endfor %}{% endif %}
                </select>
                <button type="submit" class="btn btn-lg btn-outline-dark"
                    id="add_phrase_submit">Select</button>
            </form>
        </div>
        <div class="col-6">
            <h5>Edit phrases</h5>
            <form id="edit_phrase_form" action="" method="get" class="input-group">
                <select id="edit_phrase" class="form-control" required>
                    <option disabled selected value>Select a phrase to edit</option>
                    {% if phrases %}{% for phrase in phrases %}
                    <option value="{{ phrase.id }}">{{ phrase.phrase }}</option>
                    {% endfor %}{% endif %}
                </select>
                <button type="submit" class="btn btn-lg btn-outline-dark"
                    id="edit_phrase_submit">Select</button>
            </form>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-6">
            <h5>Add translations <span class="text-muted">to phrases</span></h5>
            <form id="add_translation_form" action="" method="get" class="input-group">
                <select id="add_translation" class="form-control" required>
                    <option disabled selected value>Select a phrase to add translations</option>
                    {% if phrases %}{% for phrase in phrases %}
                    <option value="[{{ phrase.module.id }}, {{ phrase.id }}]">
                        {{ phrase.phrase }}</option>
                    {% endfor %}{% endif %}
                </select>
                <button type="submit" class="btn btn-lg btn-outline-dark"
                    id="add_translation_submit">Select</button>
            </form>
        </div>
        <div class="col-6">
            <h5>Edit translations</h5>
            <form id="edit_translation_form" action="" method="get" class="input-group">
                <select id="edit_translation" class="form-control" required>
                    <option vdisabled selected value>Select a translation to edit</option>
                    {% if translations %}{% for translation in translations %}
                    <option value="{{ translation.id }}">{{ translation }}</option>
                    {% endfor %}{% endif %}
                </select>
                <button type="submit" class="btn btn-lg btn-outline-dark"
                    id="edit_translation_submit">Select</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}


{% block footer %}
    {% if user.is_superuser %}
        <div class="container-fluid">
            <div class="row p-3">
                <div class="col-6">
                    <p class="fs-5"><span class="text-danger fw-bolder">
                        Warning</span> Mass editing is only suitable for IT staff with 
                        database skills</p>
                </div>
                <div class="col-6 py-3">
                    <a href="{% url 'staff:csv_db_test' %}"
                        class="btn btn-lg btn-outline-dark w-100">
                        Mass edit database content from CSV</a>
                </div>
            </div>
        </div>
    {% endif %}
<script>
    document.addEventListener('DOMContentLoaded', function() {

        // Format action URL with id based on dropdown selection when button is clicked
        let edit_module_selector = document.getElementById('edit_module');
        document.getElementById('edit_module_submit').addEventListener('click', function() {
            let url = 'edit_module/' + edit_module_selector.value;
            document.getElementById('edit_module_form').action = url;
            // change to this Format for all options
            // "window.location.href='{% url 'staff:manage_content' %}';return false;"
        });

        let add_phrase_selector = document.getElementById('add_phrase');
        document.getElementById('add_phrase_submit').addEventListener('click', function() {
            let url = 'module/' + add_phrase_selector.value + '/add_phrase';
            document.getElementById('add_phrase_form').action = url;
        });

        let edit_phrase_selector = document.getElementById('edit_phrase');
        document.getElementById('edit_phrase_submit').addEventListener('click', function() {
            let url = 'edit_phrase/' + edit_phrase_selector.value;
            document.getElementById('edit_phrase_form').action = url;
        });

        let add_translation_selector = document.getElementById('add_translation');
        document.getElementById('add_translation_submit').addEventListener('click', function() {
            const obj = JSON.parse(add_translation_selector.value);
            let [module_id, phrase_id] = [obj[0], obj[1]];
            let url = 'module/' + module_id + '/phrase/' + phrase_id + '/add_translation';
            document.getElementById('add_translation_form').action = url;
        });
        
        let edit_translation_selector = document.getElementById('edit_translation');
        document.getElementById('edit_translation_submit').addEventListener('click', function() {
            let url = 'edit_translation/' + edit_translation_selector.value;
            document.getElementById('edit_translation_form').action = url;
        });
    });
</script>
{% endblock footer %}